"""

A mapping module that associates language identifiers with their corresponding interpreter classes.

This module contains a dictionary named `language_map` which serves as a mapping between programming language identifiers
(such as 'python', 'bash', 'javascript', etc.) and the classes that handle the interpretation and execution of code for those languages.

Attributes:
    language_map (dict): A dictionary where the keys are string identifiers for programming languages, and the values are
                        the respective classes derived from `BaseCodeInterpreter` or `SubprocessCodeInterpreter` that are capable of
                        processing and interpreting code in those languages. The mapping is designed to facilitate the execution of
                        code snippets in a multi-language runtime environment.

Supported Language Mappings:
    - 'python': Python
    - 'bash', 'shell', 'sh', 'zsh': Shell
    - 'javascript': JavaScript
    - 'html': HTML
    - 'applescript': AppleScript
    - 'r': R
    - 'powershell': PowerShell

Note: Documentation automatically generated by https://undoc.ai
"""
from .languages.applescript import AppleScript
from .languages.html import HTML
from .languages.javascript import JavaScript
from .languages.powershell import PowerShell
from .languages.python import Python
from .languages.r import R
from .languages.shell import Shell

language_map = {
    "python": Python,
    "bash": Shell,
    "shell": Shell,
    "sh": Shell,
    "zsh": Shell,
    "javascript": JavaScript,
    "html": HTML,
    "applescript": AppleScript,
    "r": R,
    "powershell": PowerShell,
}
