"""

Module that retrieves conversation file names from a specified 'conversations' directory.

    This module contains the function `get_conversations` which scans a subdirectory named 'conversations'
    within a given configuration directory for files that have a '.json' extension. The function
    primarily lists the names of JSON files which represent individual conversations. It uses the
    `get_storage_path` helper function from the `.local_storage_path` module to determine the
    absolute path to the 'conversations' directory before performing the file scan.

    Functions:
        get_conversations: Retrieves a list of '.json' files representing conversations in the
                           'conversations' subdirectory.

    How to Import:
        from <module_path> import get_conversations

    Example of module import:
        In order to use the `get_conversations` function in your code,
        include the following import statement:
        `from this_module import get_conversations`

    Expected Exceptions:
        If there are issues with accessing or reading from the 'conversations' directory, functions
        might raise `FileNotFoundError` or `PermissionError`.

Note: Documentation automatically generated by https://undoc.ai
"""
import os

from .local_storage_path import get_storage_path


def get_conversations():
    """
    Fetches a list of filenames for JSON conversation files stored in a 'conversations' subdirectory.
    This function searches for all files ending with `.json` in the subdirectory named 'conversations' within the
    application's configuration directory. It assumes that the configuration directory path is correctly set and
    accessible, and that 'conversations' subdirectory exists and contains the conversation files.
    Returns:
        list: A list of filenames (strings), each representing a conversation JSON file found in the
              'conversations' subdirectory. If no files are found or the directory does not exist, it returns an
              empty list.
    """
    conversations_dir = get_storage_path("conversations")
    json_files = [f for f in os.listdir(conversations_dir) if f.endswith(".json")]
    return json_files
