"""

Retrieves a formatted string containing user-specific information.

This function collects the current user's username, current working directory,
shell environment, and operating system. It returns a formatted string that
encapsulates this information in a human-readable format.

Returns:
    str: A string containing the collected user information, formatted with
         labels and newlines for readability.


Note: Documentation automatically generated by https://undoc.ai
"""
import getpass
import os
import platform


def get_user_info_string():
    """
    Gets the current user's information, including username, current working directory, operating system, and default shell.
        Returns:
            str: A formatted string summarizing user details.
        This function assembles information about the current user by fetching the username, the current working directory,
        the operating system type, and the default shell in use. It formats these details into a readable string and returns it.
        For example, the function might return a string like "[User Info]
    Name: jdoe
    CWD: /home/jdoe
    SHELL: /bin/bash
    OS: Linux"
        if the current user is 'jdoe' who is working in '/home/jdoe' on a Linux system with '/bin/bash' as the default shell.
    """
    username = getpass.getuser()
    current_working_directory = os.getcwd()
    operating_system = platform.system()
    default_shell = os.environ.get("SHELL")

    return f"[User Info]\nName: {username}\nCWD: {current_working_directory}\nSHELL: {default_shell}\nOS: {operating_system}"
