"""


    Merges a delta dictionary into an original dictionary recursively.

    This function will recursively navigate through the `delta` dictionary,
    merging its contents with the corresponding entries in the `original` dictionary.
    When a value for a key in `delta` is a dictionary itself, and the key exists in the
    `original` dictionary, this function will recurse and apply the changes.

    If the value is not a dictionary and the key exists, it will increment the value of
    the key in the `original` dictionary by the value from `delta`. If the key does not
    exist, it will simply set the value.

    Args:
        original (dict): The dictionary into which the deltas will be merged. Must be
                          provided as a mutable object that can be modified.
        delta (dict): The dictionary containing the changes to be merged into the original.
                      Values must be either integers (for incrementing), dictionaries
                      (for recursive merging), or other values that will be set directly.

    Returns:
        dict: The original dictionary after the delta has been merged into it.
    

Note: Documentation automatically generated by https://undoc.ai
"""
import json
import re


def merge_deltas(original, delta):
    """
    Merges a delta dictionary into an original dictionary by updating or adding key-value pairs recursively.
    This function iterates over each key-value pair in the delta dictionary. If the value is a dictionary itself, it recursively calls itself to merge this value into the corresponding value in the original dictionary. If the key already exists in the original dictionary and is not a dictionary, the values will be added together. If a key from the delta does not exist in the original dictionary, it will be added.
    Args:
        original (dict): The original dictionary to be updated with the values from the delta dictionary.
        delta (dict): The dictionary containing the changes to be applied to the original dictionary.
    Returns:
        dict: The updated original dictionary.
    """
    for key, value in delta.items():
        if isinstance(value, dict):
            if key not in original:
                original[key] = value
            else:
                merge_deltas(original[key], value)
        else:
            if key in original:
                original[key] += value
            else:
                original[key] = value
    return original
